version: "3.0"
services:
  mkdocs:
    image: problem-detection-analysis
    build:
      dockerfile: mkdocs.dockerfile
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000